name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  react-ci:
    name: React CI
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      HUSKY: 0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: cd client-mu-plugins/goodbids && npm install

      - name: Lint
        run: cd client-mu-plugins/goodbids && npm run lint

      - name: Format
        run: cd client-mu-plugins/goodbids && npm run format

      - name: Compile
        run: cd client-mu-plugins/goodbids && npm run compile
