name: CI

on:
  push:
    branches: [main, production]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  to-do:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI goes here"
