name: Production Deploy

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [production]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.CI_DEPLOY_KEY }}
          name: id_goodbidsNode
          known_hosts: unnecessary # Actions have have github.com in known_hosts by default
          config: |
            Host github.com
              HostName github.com
              IdentityFile /home/runner/.ssh/id_goodbidsNode
          if_key_exists: fail

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: production

      - name: Push to remote
        run: |
          git config --unset-all http.https://github.com/.extraheader
          git config user.name "GitHub Actions"
          git config user.email github-actions@github.com
          git remote add wpvip git@github.com:wpcomvip/goodbids.git
          git push -f wpvip production:production
